# Generated by Django 4.1.1 on 2022-11-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                ("price", models.IntegerField(null=True, verbose_name="قیمت")),
                (
                    "short_description",
                    models.CharField(
                        db_index=True,
                        max_length=400,
                        null=True,
                        verbose_name="توضیحات کوتاه",
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="توضیحات اصلی"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال / غیر فعال"),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False, verbose_name="حذف شده / حذف نشده"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, default="", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب",
                "verbose_name_plural": "کتاب ها",
            },
        ),
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="عنوان"
                    ),
                ),
                (
                    "url_title",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="عنوان در url"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال / غیر فعال"),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False, verbose_name="حذف شده / حذف نشده"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی کتاب",
                "verbose_name_plural": "دسته بندی کتاب ها",
            },
        ),
        migrations.CreateModel(
            name="BookTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="عنوان تگ"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_tags",
                        to="product.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ کتاب",
                "verbose_name_plural": "تگ های کتاب ها",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                related_name="book_categories",
                to="product.bookcategory",
                verbose_name="دسته بندی های کتاب",
            ),
        ),
    ]
