# Generated by Django 4.1.3 on 2023-07-05 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.bookcategory', verbose_name='دسته بندی والد'),
        ),
    ]
