# Generated by Django 4.1.3 on 2023-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="book_categories",
                to="product.bookcategory",
                verbose_name="دسته بندی های کتاب",
            ),
        ),
    ]
