# Generated by Django 4.1.3 on 2023-08-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                related_name="book_categories",
                to="product.bookcategory",
                verbose_name="دسته بندی های کتاب",
            ),
        ),
        migrations.AlterField(
            model_name="bookcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.bookcategory",
                verbose_name="دسته بندی والد",
            ),
        ),
    ]
