# Generated by Django 4.1.3 on 2023-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_account', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
